catch "err [throw "err]
show error
